export const seedProducts = [
  // ==================== EASTERN WEAR ====================
  {
    name: "Premium Shalwar Kameez - White",
    slug: "premium-shalwar-kameez-white",
    description: "Classic white cotton shalwar kameez with premium stitching. Perfect for everyday wear and formal occasions. Made from breathable lawn fabric ideal for Pakistani summers.",
    price: 3500,
    compareAtPrice: 4500,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&h=800&fit=crop"],
    category: "Eastern Wear",
    subcategory: "Shalwar Kameez",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Off White", hex: "#FAF9F6" }],
    stock: 50,
    featured: true,
    tags: ["shalwar-kameez", "eastern", "cotton", "formal", "white"],
    rating: 4.7,
    reviewCount: 234,
    tryOnEnabled: true,
  },
  {
    name: "Embroidered Shalwar Kameez",
    slug: "embroidered-shalwar-kameez",
    description: "Elegant shalwar kameez with intricate embroidery on collar and cuffs. Premium wash & wear fabric. Ideal for Eid, weddings, and special occasions.",
    price: 5500,
    compareAtPrice: 7000,
    images: ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&h=800&fit=crop"],
    category: "Eastern Wear",
    subcategory: "Shalwar Kameez",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy", hex: "#000080" }, { name: "Black", hex: "#000000" }, { name: "Olive", hex: "#808000" }],
    stock: 30,
    featured: true,
    tags: ["shalwar-kameez", "embroidered", "formal", "eid", "premium"],
    rating: 4.8,
    reviewCount: 178,
    tryOnEnabled: true,
  },
  {
    name: "Classic Kurta Pajama",
    slug: "classic-kurta-pajama",
    description: "Comfortable cotton kurta with matching pajama. Relaxed fit with side slits. Perfect for home, casual outings, and Friday prayers.",
    price: 2800,
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&h=800&fit=crop"],
    category: "Eastern Wear",
    subcategory: "Kurta Pajama",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Sky Blue", hex: "#87CEEB" }, { name: "Beige", hex: "#F5F5DC" }, { name: "White", hex: "#FFFFFF" }],
    stock: 45,
    featured: false,
    tags: ["kurta", "pajama", "casual", "cotton", "comfortable"],
    rating: 4.5,
    reviewCount: 156,
    tryOnEnabled: true,
  },
  {
    name: "Designer Kurta Pajama",
    slug: "designer-kurta-pajama",
    description: "Premium designer kurta pajama with subtle print pattern. Luxurious fabric with a modern cut. Stand out at any gathering.",
    price: 4200,
    compareAtPrice: 5500,
    images: ["https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=800&h=800&fit=crop"],
    category: "Eastern Wear",
    subcategory: "Kurta Pajama",
    sizes: ["M", "L", "XL"],
    colors: [{ name: "Maroon", hex: "#800000" }, { name: "Teal", hex: "#008080" }],
    stock: 20,
    featured: true,
    tags: ["kurta", "designer", "premium", "printed", "party"],
    rating: 4.6,
    reviewCount: 89,
    tryOnEnabled: true,
  },
  {
    name: "Men's 3 Piece Suit - Navy",
    slug: "mens-3-piece-suit-navy",
    description: "Complete 3-piece suit with kameez, shalwar, and waistcoat. Premium wash & wear fabric with elegant embroidered waistcoat. Perfect for weddings and formal events.",
    price: 8500,
    compareAtPrice: 11000,
    images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop"],
    category: "Eastern Wear",
    subcategory: "3 Piece Suits",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy Blue", hex: "#000080" }, { name: "Black", hex: "#000000" }],
    stock: 15,
    featured: true,
    tags: ["3-piece", "suit", "waistcoat", "wedding", "formal"],
    rating: 4.9,
    reviewCount: 67,
    tryOnEnabled: true,
  },
  {
    name: "Embroidered Waistcoat",
    slug: "embroidered-waistcoat",
    description: "Richly embroidered waistcoat in premium fabric. Pairs perfectly with plain shalwar kameez for a distinguished look at formal events.",
    price: 3200,
    images: ["https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800&h=800&fit=crop"],
    category: "Eastern Wear",
    subcategory: "Waistcoats",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Gold", hex: "#FFD700" }, { name: "Maroon", hex: "#800000" }, { name: "Black", hex: "#000000" }],
    stock: 25,
    featured: false,
    tags: ["waistcoat", "embroidered", "formal", "wedding", "eastern"],
    rating: 4.4,
    reviewCount: 93,
    tryOnEnabled: true,
  },
  // ==================== WESTERN WEAR ====================
  {
    name: "Classic Denim Jacket",
    slug: "classic-denim-jacket",
    description: "Timeless denim jacket with button closure. 100% cotton denim with slight stretch. Versatile layering piece for any season.",
    price: 4500,
    compareAtPrice: 6000,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "Jackets",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Blue", hex: "#4169E1" }, { name: "Black", hex: "#000000" }],
    stock: 35,
    featured: true,
    tags: ["jacket", "denim", "casual", "outerwear", "western"],
    rating: 4.6,
    reviewCount: 198,
    tryOnEnabled: true,
  },
  {
    name: "Leather Biker Jacket",
    slug: "leather-biker-jacket",
    description: "Premium faux leather biker jacket with asymmetric zip closure. Quilted shoulders and slim fit. The ultimate statement piece.",
    price: 7500,
    compareAtPrice: 9500,
    images: ["https://images.unsplash.com/photo-1520975954732-35dd22299614?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "Jackets",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Brown", hex: "#8B4513" }],
    stock: 18,
    featured: false,
    tags: ["jacket", "leather", "biker", "premium", "winter"],
    rating: 4.7,
    reviewCount: 124,
    tryOnEnabled: true,
  },
  {
    name: "Merino Wool Sweater",
    slug: "merino-wool-sweater",
    description: "Luxurious merino wool crewneck sweater. Naturally temperature regulating and odor resistant. Perfect for layering in cooler months.",
    price: 3800,
    compareAtPrice: 4800,
    images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "Sweaters",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Burgundy", hex: "#800020" }, { name: "Camel", hex: "#C19A6B" }, { name: "Charcoal", hex: "#36454F" }],
    stock: 40,
    featured: true,
    tags: ["sweater", "wool", "merino", "winter", "warm"],
    rating: 4.5,
    reviewCount: 167,
    tryOnEnabled: true,
  },
  {
    name: "Cotton Hoodie",
    slug: "cotton-hoodie",
    description: "Ultra-soft cotton blend hoodie with kangaroo pocket. Brushed fleece interior for warmth. Relaxed fit perfect for lounging or layering.",
    price: 2800,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "Hoodies",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Gray", hex: "#808080" }, { name: "Navy", hex: "#000080" }],
    stock: 55,
    featured: false,
    tags: ["hoodie", "casual", "cotton", "loungewear", "winter"],
    rating: 4.3,
    reviewCount: 210,
    tryOnEnabled: true,
  },
  {
    name: "Slim Fit Chinos",
    slug: "slim-fit-chinos",
    description: "Modern fit chino trousers in stretchy cotton twill. Versatile enough for office or weekend. Wrinkle-resistant finish.",
    price: 3200,
    images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "Trousers",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: [{ name: "Khaki", hex: "#C3B091" }, { name: "Navy", hex: "#000080" }, { name: "Black", hex: "#000000" }],
    stock: 60,
    featured: false,
    tags: ["chinos", "trousers", "slim-fit", "office", "casual"],
    rating: 4.4,
    reviewCount: 145,
    tryOnEnabled: true,
  },
  {
    name: "Straight Fit Jeans",
    slug: "straight-fit-jeans",
    description: "Premium denim jeans with comfortable straight fit. Dark wash with subtle whiskering. Durable construction for everyday wear.",
    price: 3500,
    compareAtPrice: 4500,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "Jeans",
    sizes: ["28", "30", "32", "34", "36"],
    colors: [{ name: "Dark Blue", hex: "#00008B" }, { name: "Black", hex: "#000000" }, { name: "Light Blue", hex: "#ADD8E6" }],
    stock: 70,
    featured: false,
    tags: ["jeans", "denim", "straight-fit", "casual", "everyday"],
    rating: 4.3,
    reviewCount: 298,
    tryOnEnabled: true,
  },
  {
    name: "Slim Fit T-Shirt",
    slug: "slim-fit-tshirt",
    description: "Essential crew neck t-shirt in premium combed cotton. Slim fit silhouette. Pre-shrunk fabric that maintains shape wash after wash.",
    price: 1200,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Black", hex: "#000000" }, { name: "Gray", hex: "#808080" }],
    stock: 100,
    featured: false,
    tags: ["tshirt", "basic", "cotton", "slim-fit", "essential"],
    rating: 4.2,
    reviewCount: 412,
    tryOnEnabled: true,
  },
  {
    name: "Polo Shirt",
    slug: "polo-shirt",
    description: "Classic polo shirt in breathable pique cotton. Ribbed collar and cuffs with 2-button placket. Smart casual essential.",
    price: 1800,
    images: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "T-Shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy", hex: "#000080" }, { name: "White", hex: "#FFFFFF" }, { name: "Red", hex: "#FF0000" }],
    stock: 65,
    featured: false,
    tags: ["polo", "smart-casual", "cotton", "collar", "classic"],
    rating: 4.4,
    reviewCount: 178,
    tryOnEnabled: true,
  },
  {
    name: "Formal Dress Shirt",
    slug: "formal-dress-shirt",
    description: "Crisp cotton dress shirt with spread collar. Wrinkle-free fabric, perfect for office and formal events. Tailored fit.",
    price: 2500,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=800&fit=crop"],
    category: "Western Wear",
    subcategory: "Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Light Blue", hex: "#ADD8E6" }, { name: "Pink", hex: "#FFB6C1" }],
    stock: 45,
    featured: false,
    tags: ["shirt", "formal", "office", "dress-shirt", "cotton"],
    rating: 4.5,
    reviewCount: 203,
    tryOnEnabled: true,
  },
  // ==================== FOOTWEAR ====================
  {
    name: "Traditional Peshawari Chappal",
    slug: "traditional-peshawari-chappal",
    description: "Handcrafted genuine leather Peshawari chappal. Traditional design with modern comfort. Perfect with shalwar kameez.",
    price: 2500,
    images: ["https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&h=800&fit=crop"],
    category: "Footwear",
    subcategory: "Eastern Sandals",
    sizes: ["7", "8", "9", "10", "11"],
    colors: [{ name: "Brown", hex: "#8B4513" }, { name: "Black", hex: "#000000" }, { name: "Tan", hex: "#D2B48C" }],
    stock: 35,
    featured: true,
    tags: ["chappal", "peshawari", "leather", "eastern", "handmade"],
    rating: 4.6,
    reviewCount: 189,
    tryOnEnabled: false,
  },
  {
    name: "Kolhapuri Sandals",
    slug: "kolhapuri-sandals",
    description: "Classic leather Kolhapuri sandals with hand-stitched design. Comfortable flat sole. A timeless eastern footwear choice.",
    price: 1800,
    images: ["https://images.unsplash.com/photo-1529810313688-44ea1c2d81d4?w=800&h=800&fit=crop"],
    category: "Footwear",
    subcategory: "Eastern Sandals",
    sizes: ["7", "8", "9", "10", "11"],
    colors: [{ name: "Tan", hex: "#D2B48C" }, { name: "Brown", hex: "#8B4513" }],
    stock: 28,
    featured: false,
    tags: ["kolhapuri", "sandals", "leather", "eastern", "casual"],
    rating: 4.3,
    reviewCount: 112,
    tryOnEnabled: false,
  },
  {
    name: "Oxford Formal Shoes",
    slug: "oxford-formal-shoes",
    description: "Classic Oxford shoes in polished leather. Closed lacing system with leather sole. Essential for business and formal occasions.",
    price: 6500,
    compareAtPrice: 8000,
    images: ["https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&h=800&fit=crop"],
    category: "Footwear",
    subcategory: "Formal Shoes",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Brown", hex: "#8B4513" }],
    stock: 22,
    featured: true,
    tags: ["oxford", "formal", "leather", "office", "classic"],
    rating: 4.7,
    reviewCount: 156,
    tryOnEnabled: false,
  },
  {
    name: "White Sneakers",
    slug: "white-sneakers",
    description: "Clean minimal white sneakers with cushioned sole. Premium synthetic upper. Versatile everyday shoes that go with everything.",
    price: 3500,
    images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=800&fit=crop"],
    category: "Footwear",
    subcategory: "Casual Shoes",
    sizes: ["7", "8", "9", "10", "11"],
    colors: [{ name: "White", hex: "#FFFFFF" }, { name: "White/Black", hex: "#F5F5F5" }],
    stock: 40,
    featured: false,
    tags: ["sneakers", "white", "casual", "minimal", "everyday"],
    rating: 4.4,
    reviewCount: 267,
    tryOnEnabled: false,
  },
  {
    name: "Running Shoes",
    slug: "running-shoes",
    description: "Lightweight performance running shoes with responsive cushioning. Breathable mesh upper. Ideal for daily runs and workouts.",
    price: 5500,
    compareAtPrice: 7000,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop"],
    category: "Footwear",
    subcategory: "Sneakers",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: [{ name: "Red", hex: "#FF0000" }, { name: "Black", hex: "#000000" }, { name: "Blue", hex: "#0000FF" }],
    stock: 33,
    featured: false,
    tags: ["shoes", "running", "sports", "athletic", "gym"],
    rating: 4.6,
    reviewCount: 312,
    tryOnEnabled: false,
  },
  {
    name: "Loafers",
    slug: "classic-loafers",
    description: "Slip-on leather loafers with cushioned insole. Perfect for smart casual occasions. Pairs well with both eastern and western outfits.",
    price: 4500,
    images: ["https://images.unsplash.com/photo-1616406432452-07bc5938b8a5?w=800&h=800&fit=crop"],
    category: "Footwear",
    subcategory: "Casual Shoes",
    sizes: ["7", "8", "9", "10", "11"],
    colors: [{ name: "Brown", hex: "#8B4513" }, { name: "Black", hex: "#000000" }, { name: "Tan", hex: "#D2B48C" }],
    stock: 25,
    featured: false,
    tags: ["loafers", "slip-on", "leather", "smart-casual", "versatile"],
    rating: 4.5,
    reviewCount: 134,
    tryOnEnabled: false,
  },
  // ==================== ACCESSORIES ====================
  {
    name: "Oud Wood Perfume",
    slug: "oud-wood-perfume",
    description: "Premium oud-based fragrance with woody and musky notes. Long-lasting 8+ hour performance. A signature scent for the modern man.",
    price: 4500,
    compareAtPrice: 5500,
    images: ["https://images.unsplash.com/photo-1594035910387-fbd1a485b12e?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Perfumes",
    sizes: ["50ml", "100ml"],
    colors: [],
    stock: 30,
    featured: true,
    tags: ["perfume", "oud", "fragrance", "luxury", "long-lasting"],
    rating: 4.8,
    reviewCount: 234,
    tryOnEnabled: false,
  },
  {
    name: "Fresh Aqua Cologne",
    slug: "fresh-aqua-cologne",
    description: "Refreshing aquatic cologne with citrus and marine notes. Perfect for daily wear. Light and invigorating scent for summer.",
    price: 2500,
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Perfumes",
    sizes: ["50ml", "100ml", "200ml"],
    colors: [],
    stock: 45,
    featured: false,
    tags: ["cologne", "aqua", "fresh", "daily", "summer"],
    rating: 4.3,
    reviewCount: 156,
    tryOnEnabled: false,
  },
  {
    name: "Aviator Sunglasses",
    slug: "aviator-sunglasses",
    description: "Classic aviator sunglasses with UV400 protection. Polarized lenses reduce glare. Lightweight metal frame with adjustable nose pads.",
    price: 2800,
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Sunglasses",
    sizes: [],
    colors: [{ name: "Gold/Green", hex: "#FFD700" }, { name: "Silver/Blue", hex: "#C0C0C0" }, { name: "Black", hex: "#000000" }],
    stock: 40,
    featured: true,
    tags: ["sunglasses", "aviator", "uv-protection", "polarized", "classic"],
    rating: 4.5,
    reviewCount: 189,
    tryOnEnabled: true,
  },
  {
    name: "Wayfarer Sunglasses",
    slug: "wayfarer-sunglasses",
    description: "Iconic wayfarer-style sunglasses with UV400 protection. Durable acetate frame. Timeless design that suits every face shape.",
    price: 2200,
    images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Sunglasses",
    sizes: [],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Tortoise", hex: "#8B4513" }],
    stock: 35,
    featured: false,
    tags: ["sunglasses", "wayfarer", "uv-protection", "casual", "trendy"],
    rating: 4.4,
    reviewCount: 145,
    tryOnEnabled: true,
  },
  {
    name: "Premium Baseball Cap",
    slug: "premium-baseball-cap",
    description: "Premium cotton twill baseball cap with adjustable strap. Embroidered logo detail. Classic 6-panel construction.",
    price: 1200,
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c334e67a?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Caps & Hats",
    sizes: ["One Size"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Navy", hex: "#000080" }, { name: "White", hex: "#FFFFFF" }],
    stock: 60,
    featured: false,
    tags: ["cap", "baseball", "casual", "cotton", "adjustable"],
    rating: 4.2,
    reviewCount: 178,
    tryOnEnabled: true,
  },
  {
    name: "Pakol Hat",
    slug: "pakol-hat",
    description: "Traditional wool Pakol hat. Rolled brim design. Warm and stylish headwear with cultural significance.",
    price: 1500,
    images: ["https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Caps & Hats",
    sizes: ["One Size"],
    colors: [{ name: "Brown", hex: "#8B4513" }, { name: "Gray", hex: "#808080" }, { name: "Cream", hex: "#FFFDD0" }],
    stock: 25,
    featured: false,
    tags: ["pakol", "hat", "traditional", "wool", "eastern"],
    rating: 4.3,
    reviewCount: 67,
    tryOnEnabled: true,
  },
  {
    name: "Genuine Leather Belt",
    slug: "genuine-leather-belt",
    description: "Full-grain genuine leather belt with brushed nickel buckle. 1.5 inch width. Classic design that pairs with any outfit — eastern or western.",
    price: 1800,
    images: ["https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Belts",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Brown", hex: "#8B4513" }, { name: "Black", hex: "#000000" }],
    stock: 55,
    featured: false,
    tags: ["belt", "leather", "genuine", "formal", "casual"],
    rating: 4.6,
    reviewCount: 198,
    tryOnEnabled: false,
  },
  {
    name: "Automatic Buckle Belt",
    slug: "automatic-buckle-belt",
    description: "Premium leather belt with automatic ratchet buckle. No holes — adjusts to any size perfectly. Sleek modern design.",
    price: 2200,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Belts",
    sizes: ["One Size"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Brown", hex: "#8B4513" }],
    stock: 40,
    featured: false,
    tags: ["belt", "automatic", "ratchet", "leather", "modern"],
    rating: 4.4,
    reviewCount: 134,
    tryOnEnabled: false,
  },
  {
    name: "Chronograph Watch",
    slug: "chronograph-watch",
    description: "Stainless steel chronograph watch with Japanese movement. Water resistant to 50m. Sapphire crystal glass. A statement timepiece.",
    price: 8500,
    compareAtPrice: 12000,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Watches",
    sizes: [],
    colors: [{ name: "Silver", hex: "#C0C0C0" }, { name: "Gold", hex: "#FFD700" }, { name: "Black", hex: "#000000" }],
    stock: 12,
    featured: true,
    tags: ["watch", "chronograph", "stainless-steel", "luxury", "waterproof"],
    rating: 4.8,
    reviewCount: 98,
    tryOnEnabled: false,
  },
  {
    name: "Digital Sports Watch",
    slug: "digital-sports-watch",
    description: "Rugged digital sports watch with multiple functions. Stopwatch, alarm, backlight, and date display. Water resistant to 100m.",
    price: 3500,
    images: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&h=800&fit=crop"],
    category: "Accessories",
    subcategory: "Watches",
    sizes: [],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Army Green", hex: "#4B5320" }],
    stock: 30,
    featured: false,
    tags: ["watch", "digital", "sports", "rugged", "waterproof"],
    rating: 4.3,
    reviewCount: 167,
    tryOnEnabled: false,
  },
];
